sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - kevrodrigues116@gmail.com
    on_success: never
    on_failure: always
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage